blank_lines_upper_bound = 2
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
match_block_trailing_comma = true
max_width = 140
merge_derives = false
overflow_delimited_expr = true
reorder_impl_items = true
single_line_if_else_max_width = 80
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
