[package]
name = "ferium"
resolver = "2"
version = "4.5.2"
edition = "2021"
rust-version = "1.79"
authors = [
    "Michael Ziminsky (Z)",
    "Ilesh Thiada (theRookieCoder) <ileshkt@gmail.com>",
    "薛詠謙 (KyleUltimate)",
    "Daniel Hauck (SolidTux)",
]
description = "Fast CLI program for managing Minecraft mods and modpacks from Modrinth, CurseForge, and Github Releases"
exclude = [".github", "tests", "media"]
repository = "https://github.com/gorilla-devs/ferium"
categories = ["command-line-utilities"]
readme = "README.md"
license = "MPL-2.0"
keywords = ["minecraft", "mod-manager", "modrinth", "curseforge", "github"]

[features]
default = []
gui = ["rfd"]

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
clap_complete = "4.5"
colored = "2.1"
dialoguer = "0.11"
dirs = "5"
fs_extra = "1.3"
indicatif = "0.17"
itertools = "0.13"
once_cell = "1.19"
relibium = { version = "2", path = "../lib" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
size = "0.4"
url = "2.5"

reqwest = { version = "0.12", default-features = false, features = [
    "rustls-tls",
] }
rfd = { version = "0.14", default-features = false, optional = true, features = [
    "xdg-portal",
    "tokio",
] }
tokio = { version = "1.38", default-features = false, features = [
    "rt-multi-thread",
] }

[dev-dependencies]
rand = "0.8"

[profile.release]
codegen-units = 1
strip = true
lto = true

[lints.rust]
# Hacky workaround for RA to allow analyzing both `cfg` and `not(cfg)` code
# by defining an `ide` cfg attribute. This allows code completion and assist
# to work, but doesn't enable error checking or recognize imports
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(ide)'] }
