/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiResponseOfMinecraftGameVersion {
    #[serde(rename = "data")]
    pub data: models::MinecraftGameVersion,
}

impl ApiResponseOfMinecraftGameVersion {
    pub fn new(data: models::MinecraftGameVersion) -> Self {
        Self {
            data,
        }
    }
}

