/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Category {
    #[serde(rename = "id")]
    pub id: u64,
    #[serde(rename = "gameId")]
    pub game_id: u64,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "url")]
    pub url: ::url::Url,
    #[serde(rename = "iconUrl")]
    pub icon_url: ::url::Url,
    #[serde(rename = "dateModified")]
    pub date_modified: String,
    #[serde(rename = "isClass")]
    pub is_class: bool,
    #[serde(rename = "classId")]
    pub class_id: u64,
    #[serde(rename = "parentCategoryId")]
    pub parent_category_id: u64,
    #[serde(rename = "displayIndex")]
    pub display_index: u64,
}

impl Category {
    pub fn new(id: u64, game_id: u64, name: String, slug: String, url: ::url::Url, icon_url: ::url::Url, date_modified: String, is_class: bool, class_id: u64, parent_category_id: u64, display_index: u64) -> Self {
        Self {
            id,
            game_id,
            name,
            slug,
            url,
            icon_url,
            date_modified,
            is_class,
            class_id,
            parent_category_id,
            display_index,
        }
    }
}

