/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.250410
 * 
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Category {
    /// The category id
    #[serde(rename = "id")]
    pub id: u32,
    /// The game id related to the category
    #[serde(rename = "gameId")]
    pub game_id: u32,
    /// Category name
    #[serde(rename = "name")]
    pub name: String,
    /// The category slug as it appear in the URL
    #[serde(rename = "slug")]
    pub slug: String,
    /// The category URL
    #[serde(rename = "url")]
    pub url: ::url::Url,
    /// URL for the category icon
    #[serde(rename = "iconUrl")]
    pub icon_url: ::url::Url,
    /// Last modified date of the category
    #[serde(rename = "dateModified")]
    pub date_modified: String,
    /// A top level category for other categories
    #[serde(rename = "isClass", skip_serializing_if = "Option::is_none")]
    pub is_class: Option<bool>,
    /// The class id of the category, meaning - the class of which this category is under
    #[serde(rename = "classId", skip_serializing_if = "Option::is_none")]
    pub class_id: Option<u32>,
    /// The parent category for this category
    #[serde(rename = "parentCategoryId", skip_serializing_if = "Option::is_none")]
    pub parent_category_id: Option<u32>,
    /// The display index for this category
    #[serde(rename = "displayIndex", skip_serializing_if = "Option::is_none")]
    pub display_index: Option<u32>,
}

impl Category {
    #[allow(clippy::too_many_arguments)]
    pub fn new(id: u32, game_id: u32, name: String, slug: String, url: ::url::Url, icon_url: ::url::Url, date_modified: String) -> Self {
        Self {
            id,
            game_id,
            name,
            slug,
            url,
            icon_url,
            date_modified,
            is_class: None,
            class_id: None,
            parent_category_id: None,
            display_index: None,
        }
    }
}

