/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.240719
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// CoreStatus Possible enum values:  * 1 = Draft  * 2 = Test  * 3 = PendingReview  * 4 = Rejected  * 5 = Approved  * 6 = Live 
#[derive(Default, Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[derive(serde_repr::Serialize_repr, serde_repr::Deserialize_repr)]
#[repr(u8)]
pub enum CoreStatus {
    #[default]
    Draft = 1,
    Test = 2,
    PendingReview = 3,
    Rejected = 4,
    Approved = 5,
    Live = 6,
}

impl std::fmt::Display for CoreStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            Self::Draft => "1",
            Self::Test => "2",
            Self::PendingReview => "3",
            Self::Rejected => "4",
            Self::Approved => "5",
            Self::Live => "6",
        })
    }
}

