/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.240719
 * 
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeaturedModsResponse {
    #[serde(rename = "featured", default)]
    pub featured: Vec<models::Mod>,
    #[serde(rename = "popular", default)]
    pub popular: Vec<models::Mod>,
    #[serde(rename = "recentlyUpdated", default)]
    pub recently_updated: Vec<models::Mod>,
}

impl FeaturedModsResponse {
    #[allow(clippy::too_many_arguments)]
    pub fn new(featured: Vec<models::Mod>, popular: Vec<models::Mod>, recently_updated: Vec<models::Mod>) -> Self {
        Self {
            featured,
            popular,
            recently_updated,
        }
    }
}

