/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.240719
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// Possible enum values:  * 1 = EmbeddedLibrary  * 2 = OptionalDependency  * 3 = RequiredDependency  * 4 = Tool  * 5 = Incompatible  * 6 = Include 
#[derive(Default, Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[derive(serde_repr::Serialize_repr, serde_repr::Deserialize_repr)]
#[repr(u8)]
pub enum FileRelationType {
    #[default]
    EmbeddedLibrary = 1,
    OptionalDependency = 2,
    RequiredDependency = 3,
    Tool = 4,
    Incompatible = 5,
    Include = 6,
}

impl std::fmt::Display for FileRelationType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            Self::EmbeddedLibrary => "1",
            Self::OptionalDependency => "2",
            Self::RequiredDependency => "3",
            Self::Tool => "4",
            Self::Incompatible => "5",
            Self::Include => "6",
        })
    }
}

