/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.240719
 * 
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileIndex {
    #[serde(rename = "gameVersion")]
    pub game_version: String,
    #[serde(rename = "fileId")]
    pub file_id: u64,
    #[serde(rename = "filename")]
    pub filename: String,
    #[serde(rename = "releaseType")]
    pub release_type: models::FileReleaseType,
    #[serde(rename = "gameVersionTypeId", skip_serializing_if = "Option::is_none")]
    pub game_version_type_id: Option<u64>,
    #[serde(rename = "modLoader")]
    pub mod_loader: models::ModLoaderType,
}

impl FileIndex {
    #[allow(clippy::too_many_arguments)]
    pub fn new(game_version: String, file_id: u64, filename: String, release_type: models::FileReleaseType, mod_loader: models::ModLoaderType) -> Self {
        Self {
            game_version,
            file_id,
            filename,
            release_type,
            mod_loader,
            game_version_type_id: None,
        }
    }
}

