/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.240719
 * 
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileHash {
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "algo")]
    pub algo: models::HashAlgo,
}

impl FileHash {
    #[allow(clippy::too_many_arguments)]
    pub fn new(value: String, algo: models::HashAlgo) -> Self {
        Self {
            value,
            algo,
        }
    }
}

