/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Default, Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FileReleaseType {
    #[default]
    #[serde(rename = "1")]
    Release,
    #[serde(rename = "2")]
    Beta,
    #[serde(rename = "3")]
    Alpha,
}

impl std::fmt::Display for FileReleaseType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            Self::Release => "1",
            Self::Beta => "2",
            Self::Alpha => "3",
        })
    }
}

