/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.250410
 * 
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FingerprintMatch {
    #[serde(rename = "id")]
    pub id: u32,
    #[serde(rename = "file")]
    pub file: models::File,
    #[serde(rename = "latestFiles", default)]
    pub latest_files: Vec<models::File>,
}

impl FingerprintMatch {
    #[allow(clippy::too_many_arguments)]
    pub fn new(id: u32, file: models::File, latest_files: Vec<models::File>) -> Self {
        Self {
            id,
            file,
            latest_files,
        }
    }
}

