/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FingerprintMatch {
    #[serde(rename = "id")]
    pub id: u64,
    #[serde(rename = "file")]
    pub file: models::File,
    #[serde(rename = "latestFiles")]
    pub latest_files: Vec<models::File>,
}

impl FingerprintMatch {
    pub fn new(id: u64, file: models::File, latest_files: Vec<models::File>) -> Self {
        Self {
            id,
            file,
            latest_files,
        }
    }
}

