/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FolderFingerprint {
    #[serde(rename = "foldername")]
    pub foldername: String,
    #[serde(rename = "fingerprints", default)]
    pub fingerprints: Vec<u64>,
}

impl FolderFingerprint {
    pub fn new(foldername: String, fingerprints: Vec<u64>) -> Self {
        Self {
            foldername,
            fingerprints,
        }
    }
}

