/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.250410
 * 
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FolderFingerprint {
    #[serde(rename = "foldername")]
    pub foldername: String,
    #[serde(rename = "fingerprints", default)]
    pub fingerprints: Vec<u32>,
}

impl FolderFingerprint {
    #[allow(clippy::too_many_arguments)]
    pub fn new(foldername: String, fingerprints: Vec<u32>) -> Self {
        Self {
            foldername,
            fingerprints,
        }
    }
}

