/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Default, Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GameVersionStatus {
    #[default]
    #[serde(rename = "1")]
    Approved,
    #[serde(rename = "2")]
    Deleted,
    #[serde(rename = "3")]
    New,
}

impl std::fmt::Display for GameVersionStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            Self::Approved => "1",
            Self::Deleted => "2",
            Self::New => "3",
        })
    }
}

