/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.250410
 * 
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GameVersionType {
    #[serde(rename = "id")]
    pub id: u32,
    #[serde(rename = "gameId")]
    pub game_id: u32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "isSyncable")]
    pub is_syncable: bool,
    #[serde(rename = "status")]
    pub status: models::GameVersionTypeStatus,
}

impl GameVersionType {
    #[allow(clippy::too_many_arguments)]
    pub fn new(id: u32, game_id: u32, name: String, slug: String, is_syncable: bool, status: models::GameVersionTypeStatus) -> Self {
        Self {
            id,
            game_id,
            name,
            slug,
            is_syncable,
            status,
        }
    }
}

