/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.240719
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GameVersionsByType {
    #[serde(rename = "type")]
    pub r#type: u32,
    #[serde(rename = "versions", default)]
    pub versions: Vec<String>,
}

impl GameVersionsByType {
    pub fn new(r#type: u32, versions: Vec<String>) -> Self {
        Self {
            r#type,
            versions,
        }
    }
}

