/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.240719
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GameAssets {
    #[serde(rename = "iconUrl")]
    pub icon_url: ::url::Url,
    #[serde(rename = "titleUrl")]
    pub title_url: ::url::Url,
    #[serde(rename = "coverUrl")]
    pub cover_url: ::url::Url,
}

impl GameAssets {
    pub fn new(icon_url: ::url::Url, title_url: ::url::Url, cover_url: ::url::Url) -> Self {
        Self {
            icon_url,
            title_url,
            cover_url,
        }
    }
}

