/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.250410
 * 
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetModsByIdsListRequestBody {
    #[serde(rename = "modIds", default)]
    pub mod_ids: Vec<u64>,
}

impl GetModsByIdsListRequestBody {
    #[allow(clippy::too_many_arguments)]
    pub fn new(mod_ids: Vec<u64>) -> Self {
        Self {
            mod_ids,
        }
    }
}

