/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.240719
 * 
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetModFilesResponse {
    /// The response data
    #[serde(rename = "data", default)]
    pub data: Vec<models::File>,
    #[serde(rename = "pagination")]
    pub pagination: models::Pagination,
}

impl GetModFilesResponse {
    #[allow(clippy::too_many_arguments)]
    pub fn new(data: Vec<models::File>, pagination: models::Pagination) -> Self {
        Self {
            data,
            pagination,
        }
    }
}

