/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.250410
 * 
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetModFileChangelogResponse {
    #[serde(rename = "data")]
    pub data: String,
}

impl GetModFileChangelogResponse {
    #[allow(clippy::too_many_arguments)]
    pub fn new(data: String) -> Self {
        Self {
            data,
        }
    }
}

