/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetModsByIdsListRequestBody {
    #[serde(rename = "modIds")]
    pub mod_ids: Vec<u64>,
}

impl GetModsByIdsListRequestBody {
    pub fn new(mod_ids: Vec<u64>) -> Self {
        Self {
            mod_ids,
        }
    }
}

