/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetFingerprintMatchesRequestBody {
    /// list of murmur2 hashes with seed 1
    #[serde(rename = "fingerprints")]
    pub fingerprints: Vec<u64>,
}

impl GetFingerprintMatchesRequestBody {
    pub fn new(fingerprints: Vec<u64>) -> Self {
        Self {
            fingerprints,
        }
    }
}

