/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetModFilesRequestBody {
    #[serde(rename = "fileIds")]
    pub file_ids: Vec<u32>,
}

impl GetModFilesRequestBody {
    pub fn new(file_ids: Vec<u32>) -> Self {
        Self {
            file_ids,
        }
    }
}

