/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetVersionsResponse {
    /// The response data
    #[serde(rename = "data")]
    pub data: Vec<models::GameVersionsByType>,
}

impl GetVersionsResponse {
    pub fn new(data: Vec<models::GameVersionsByType>) -> Self {
        Self {
            data,
        }
    }
}

