/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.240719
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MinecraftModLoaderVersion {
    #[serde(rename = "id")]
    pub id: u64,
    #[serde(rename = "gameVersionId")]
    pub game_version_id: u64,
    #[serde(rename = "minecraftGameVersionId")]
    pub minecraft_game_version_id: u64,
    #[serde(rename = "forgeVersion")]
    pub forge_version: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "type")]
    pub r#type: models::ModLoaderType,
    #[serde(rename = "downloadUrl")]
    pub download_url: ::url::Url,
    #[serde(rename = "filename")]
    pub filename: String,
    #[serde(rename = "installMethod")]
    pub install_method: models::ModLoaderInstallMethod,
    #[serde(rename = "latest")]
    pub latest: bool,
    #[serde(rename = "recommended")]
    pub recommended: bool,
    #[serde(rename = "approved")]
    pub approved: bool,
    #[serde(rename = "dateModified")]
    pub date_modified: String,
    #[serde(rename = "mavenVersionString")]
    pub maven_version_string: String,
    #[serde(rename = "versionJson")]
    pub version_json: String,
    #[serde(rename = "librariesInstallLocation")]
    pub libraries_install_location: String,
    #[serde(rename = "minecraftVersion")]
    pub minecraft_version: String,
    #[serde(rename = "additionalFilesJson")]
    pub additional_files_json: String,
    #[serde(rename = "modLoaderGameVersionId")]
    pub mod_loader_game_version_id: u64,
    #[serde(rename = "modLoaderGameVersionTypeId")]
    pub mod_loader_game_version_type_id: u64,
    #[serde(rename = "modLoaderGameVersionStatus")]
    pub mod_loader_game_version_status: models::GameVersionStatus,
    #[serde(rename = "modLoaderGameVersionTypeStatus")]
    pub mod_loader_game_version_type_status: models::GameVersionTypeStatus,
    #[serde(rename = "mcGameVersionId")]
    pub mc_game_version_id: u64,
    #[serde(rename = "mcGameVersionTypeId")]
    pub mc_game_version_type_id: u64,
    #[serde(rename = "mcGameVersionStatus")]
    pub mc_game_version_status: models::GameVersionStatus,
    #[serde(rename = "mcGameVersionTypeStatus")]
    pub mc_game_version_type_status: models::GameVersionTypeStatus,
    #[serde(rename = "installProfileJson")]
    pub install_profile_json: String,
}

impl MinecraftModLoaderVersion {
    pub fn new(id: u64, game_version_id: u64, minecraft_game_version_id: u64, forge_version: String, name: String, r#type: models::ModLoaderType, download_url: ::url::Url, filename: String, install_method: models::ModLoaderInstallMethod, latest: bool, recommended: bool, approved: bool, date_modified: String, maven_version_string: String, version_json: String, libraries_install_location: String, minecraft_version: String, additional_files_json: String, mod_loader_game_version_id: u64, mod_loader_game_version_type_id: u64, mod_loader_game_version_status: models::GameVersionStatus, mod_loader_game_version_type_status: models::GameVersionTypeStatus, mc_game_version_id: u64, mc_game_version_type_id: u64, mc_game_version_status: models::GameVersionStatus, mc_game_version_type_status: models::GameVersionTypeStatus, install_profile_json: String) -> Self {
        Self {
            id,
            game_version_id,
            minecraft_game_version_id,
            forge_version,
            name,
            r#type,
            download_url,
            filename,
            install_method,
            latest,
            recommended,
            approved,
            date_modified,
            maven_version_string,
            version_json,
            libraries_install_location,
            minecraft_version,
            additional_files_json,
            mod_loader_game_version_id,
            mod_loader_game_version_type_id,
            mod_loader_game_version_status,
            mod_loader_game_version_type_status,
            mc_game_version_id,
            mc_game_version_type_id,
            mc_game_version_status,
            mc_game_version_type_status,
            install_profile_json,
        }
    }
}

