/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Default, Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[derive(serde_repr::Serialize_repr, serde_repr::Deserialize_repr)]
#[repr(u8)]
pub enum ModStatus {
    #[default]
    New = 1,
    ChangesRequired = 2,
    UnderSoftReview = 3,
    Approved = 4,
    Rejected = 5,
    ChangesMade = 6,
    Inactive = 7,
    Abandoned = 8,
    Deleted = 9,
    UnderReview = 10,
}

impl std::fmt::Display for ModStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            Self::New => "1",
            Self::ChangesRequired => "2",
            Self::UnderSoftReview => "3",
            Self::Approved => "4",
            Self::Rejected => "5",
            Self::ChangesMade => "6",
            Self::Inactive => "7",
            Self::Abandoned => "8",
            Self::Deleted => "9",
            Self::UnderReview => "10",
        })
    }
}

