/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Default, Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ModLoaderInstallMethod {
    #[default]
    #[serde(rename = "1")]
    ForgeInstaller,
    #[serde(rename = "2")]
    ForgeJarInstall,
    #[serde(rename = "3")]
    ForgeInstallerV2,
    #[serde(rename = "4")]
    FabricInstaller,
}

impl std::fmt::Display for ModLoaderInstallMethod {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            Self::ForgeInstaller => "1",
            Self::ForgeJarInstall => "2",
            Self::ForgeInstallerV2 => "3",
            Self::FabricInstaller => "4",
        })
    }
}

