/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Default, Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ModLoaderType {
    #[default]
    #[serde(rename = "0")]
    Any,
    #[serde(rename = "1")]
    Forge,
    #[serde(rename = "2")]
    Cauldron,
    #[serde(rename = "3")]
    LiteLoader,
    #[serde(rename = "4")]
    Fabric,
    #[serde(rename = "5")]
    Quilt,
    #[serde(rename = "6")]
    NeoForge,
}

impl std::fmt::Display for ModLoaderType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            Self::Any => "0",
            Self::Forge => "1",
            Self::Cauldron => "2",
            Self::LiteLoader => "3",
            Self::Fabric => "4",
            Self::Quilt => "5",
            Self::NeoForge => "6",
        })
    }
}

