/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.250410
 * 
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModAuthor {
    #[serde(rename = "id")]
    pub id: u32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "url")]
    pub url: ::url::Url,
    #[serde(rename = "avatarUrl")]
    pub avatar_url: ::url::Url,
}

impl ModAuthor {
    #[allow(clippy::too_many_arguments)]
    pub fn new(id: u32, name: String, url: ::url::Url, avatar_url: ::url::Url) -> Self {
        Self {
            id,
            name,
            url,
            avatar_url,
        }
    }
}

