/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.240719
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModAuthor {
    #[serde(rename = "id")]
    pub id: u64,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "url")]
    pub url: ::url::Url,
}

impl ModAuthor {
    pub fn new(id: u64, name: String, url: ::url::Url) -> Self {
        Self {
            id,
            name,
            url,
        }
    }
}

