/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Default, Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ModStatus {
    #[default]
    #[serde(rename = "1")]
    New,
    #[serde(rename = "2")]
    ChangesRequired,
    #[serde(rename = "3")]
    UnderSoftReview,
    #[serde(rename = "4")]
    Approved,
    #[serde(rename = "5")]
    Rejected,
    #[serde(rename = "6")]
    ChangesMade,
    #[serde(rename = "7")]
    Inactive,
    #[serde(rename = "8")]
    Abandoned,
    #[serde(rename = "9")]
    Deleted,
    #[serde(rename = "10")]
    UnderReview,
}

impl std::fmt::Display for ModStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            Self::New => "1",
            Self::ChangesRequired => "2",
            Self::UnderSoftReview => "3",
            Self::Approved => "4",
            Self::Rejected => "5",
            Self::ChangesMade => "6",
            Self::Inactive => "7",
            Self::Abandoned => "8",
            Self::Deleted => "9",
            Self::UnderReview => "10",
        })
    }
}

