/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.240719
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// ModLoaderInstallMethod Possible enum values:  * 1 = ForgeInstaller  * 2 = ForgeJarInstall  * 3 = ForgeInstallerV2  * 4 = FabricInstaller 
#[derive(Default, Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[derive(serde_repr::Serialize_repr, serde_repr::Deserialize_repr)]
#[repr(u8)]
pub enum ModLoaderInstallMethod {
    #[default]
    ForgeInstaller = 1,
    ForgeJarInstall = 2,
    ForgeInstallerV2 = 3,
    FabricInstaller = 4,
}

impl std::fmt::Display for ModLoaderInstallMethod {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            Self::ForgeInstaller => "1",
            Self::ForgeJarInstall => "2",
            Self::ForgeInstallerV2 => "3",
            Self::FabricInstaller => "4",
        })
    }
}

