/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Default, Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ModsSearchSortField {
    #[default]
    #[serde(rename = "1")]
    Featured,
    #[serde(rename = "2")]
    Popularity,
    #[serde(rename = "3")]
    LastUpdated,
    #[serde(rename = "4")]
    Name,
    #[serde(rename = "5")]
    Author,
    #[serde(rename = "6")]
    TotalDownloads,
    #[serde(rename = "7")]
    Category,
    #[serde(rename = "8")]
    GameVersion,
}

impl std::fmt::Display for ModsSearchSortField {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            Self::Featured => "1",
            Self::Popularity => "2",
            Self::LastUpdated => "3",
            Self::Name => "4",
            Self::Author => "5",
            Self::TotalDownloads => "6",
            Self::Category => "7",
            Self::GameVersion => "8",
        })
    }
}

