/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.240719
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// Possible enum values:  * 1 = Featured  * 2 = Popularity  * 3 = LastUpdated  * 4 = Name  * 5 = Author  * 6 = TotalDownloads  * 7 = Category  * 8 = GameVersion  * 9 = Early Access  * 10 = Featured Release  * 11 = Release Date  * 12 = Rating 
#[derive(Default, Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[derive(serde_repr::Serialize_repr, serde_repr::Deserialize_repr)]
#[repr(u8)]
pub enum ModsSearchSortField {
    #[default]
    Featured = 1,
    Popularity = 2,
    LastUpdated = 3,
    Name = 4,
    Author = 5,
    TotalDownloads = 6,
    Category = 7,
    GameVersion = 8,
    EarlyAccess = 9,
    FeaturedRelease = 10,
    ReleaseDate = 11,
    Rating = 12,
}

impl std::fmt::Display for ModsSearchSortField {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            Self::Featured => "1",
            Self::Popularity => "2",
            Self::LastUpdated => "3",
            Self::Name => "4",
            Self::Author => "5",
            Self::TotalDownloads => "6",
            Self::Category => "7",
            Self::GameVersion => "8",
            Self::EarlyAccess => "9",
            Self::FeaturedRelease => "10",
            Self::ReleaseDate => "11",
            Self::Rating => "12",
        })
    }
}

