/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// The response pagination information
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Pagination {
    /// A zero based index of the first item that is included in the response
    #[serde(rename = "index")]
    pub index: u32,
    /// The requested number of items to be included in the response
    #[serde(rename = "pageSize")]
    pub page_size: u32,
    /// The actual number of items that were included in the response
    #[serde(rename = "resultCount")]
    pub result_count: u32,
    /// The total number of items available by the request
    #[serde(rename = "totalCount")]
    pub total_count: u64,
}

impl Pagination {
    /// The response pagination information
    pub fn new(index: u32, page_size: u32, result_count: u32, total_count: u64) -> Self {
        Self {
            index,
            page_size,
            result_count,
            total_count,
        }
    }
}

