/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.250410
 * 
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use crate::models;

/// * 0 = Empty * 1 = Windows * 2 = XboxOne * 3 = XboxXS * 4 = Linux * 5 = PS4 * 6 = PS5 * 7 = Mac * 8 = IOS * 9 = TVOS * 10 = Android * 11 = Switch * 12 = WindowsServer * 13 = LinuxServer 
#[derive(Default, Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[derive(serde_repr::Serialize_repr, serde_repr::Deserialize_repr)]
#[repr(u8)]
pub enum PlatformType {
    #[default]
    Empty = 0,
    Windows = 1,
    XboxOne = 2,
    XboxXS = 3,
    Linux = 4,
    PS4 = 5,
    PS5 = 6,
    Mac = 7,
    IOS = 8,
    TVOS = 9,
    Android = 10,
    Switch = 11,
    WindowsServer = 12,
    LinuxServer = 13,
}

impl std::fmt::Display for PlatformType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            Self::Empty => "0",
            Self::Windows => "1",
            Self::XboxOne => "2",
            Self::XboxXS => "3",
            Self::Linux => "4",
            Self::PS4 => "5",
            Self::PS5 => "6",
            Self::Mac => "7",
            Self::IOS => "8",
            Self::TVOS => "9",
            Self::Android => "10",
            Self::Switch => "11",
            Self::WindowsServer => "12",
            Self::LinuxServer => "13",
        })
    }
}

