/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.250410
 * 
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RatingDetails {
    #[serde(rename = "rating", skip_serializing_if = "Option::is_none")]
    pub rating: Option<f64>,
    #[serde(rename = "totalRatings", skip_serializing_if = "Option::is_none")]
    pub total_ratings: Option<u32>,
    #[serde(rename = "positiveRatings", skip_serializing_if = "Option::is_none")]
    pub positive_ratings: Option<u32>,
    #[serde(rename = "score")]
    pub score: models::RatingScore,
}

impl RatingDetails {
    #[allow(clippy::too_many_arguments)]
    pub fn new(score: models::RatingScore) -> Self {
        Self {
            score,
            rating: None,
            total_ratings: None,
            positive_ratings: None,
        }
    }
}

