/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.250410
 * 
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use crate::models;

/// * 0 = NotEnoughReviews * 1 = OverwhelminglyPositive * 2 = VeryPositive * 3 = Positive * 4 = MostlyPositive * 5 = Mixed * 6 = MostlyNegative * 7 = Negative * 8 = VeryNegative * 9 = OverwhelminglyNegative 
#[derive(Default, Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[derive(serde_repr::Serialize_repr, serde_repr::Deserialize_repr)]
#[repr(u8)]
pub enum RatingScore {
    #[default]
    NotEnoughReviews = 0,
    OverwhelminglyPositive = 1,
    VeryPositive = 2,
    Positive = 3,
    MostlyPositive = 4,
    Mixed = 5,
    MostlyNegative = 6,
    Negative = 7,
    VeryNegative = 8,
    OverwhelminglyNegative = 9,
}

impl std::fmt::Display for RatingScore {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            Self::NotEnoughReviews => "0",
            Self::OverwhelminglyPositive => "1",
            Self::VeryPositive => "2",
            Self::Positive => "3",
            Self::MostlyPositive => "4",
            Self::Mixed => "5",
            Self::MostlyNegative => "6",
            Self::Negative => "7",
            Self::VeryNegative => "8",
            Self::OverwhelminglyNegative => "9",
        })
    }
}

