/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchModsSortFieldParameter {
    #[serde(rename = "modIds", skip_serializing_if = "Option::is_none")]
    pub mod_ids: Option<Vec<models::ModsSearchSortField>>,
}

impl SearchModsSortFieldParameter {
    pub fn new() -> SearchModsSortFieldParameter {
        SearchModsSortFieldParameter {
            mod_ids: None,
        }
    }
}

