/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.250410
 * 
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerAffiliation {
    /// Whether the server affiliate program is enabled for this mod
    #[serde(rename = "isEnabled")]
    pub is_enabled: bool,
    #[serde(rename = "isDefaultBanner")]
    pub is_default_banner: bool,
    #[serde(rename = "hasDiscount")]
    pub has_discount: bool,
    #[serde(rename = "affiliationService")]
    pub affiliation_service: models::AffiliationServiceType,
    #[serde(rename = "defaultBannerCustomTitle")]
    pub default_banner_custom_title: String,
    #[serde(rename = "customImageUrl")]
    pub custom_image_url: ::url::Url,
    #[serde(rename = "affiliationLink")]
    pub affiliation_link: ::url::Url,
}

impl ServerAffiliation {
    #[allow(clippy::too_many_arguments)]
    pub fn new(is_enabled: bool, is_default_banner: bool, has_discount: bool, affiliation_service: models::AffiliationServiceType, default_banner_custom_title: String, custom_image_url: ::url::Url, affiliation_link: ::url::Url) -> Self {
        Self {
            is_enabled,
            is_default_banner,
            has_discount,
            affiliation_service,
            default_banner_custom_title,
            custom_image_url,
            affiliation_link,
        }
    }
}

