/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.250410
 * 
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use crate::models;

/// * 1 = Mastodon * 2 = Discord * 3 = Website * 4 = Facebook * 5 = Twitter * 6 = Instagram * 7 = Patreon * 8 = Twitch * 9 = Reddit * 10 = Youtube * 11 = TikTok * 12 = Pinterest * 13 = Github * 14 = Bluesky 
#[derive(Default, Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[derive(serde_repr::Serialize_repr, serde_repr::Deserialize_repr)]
#[repr(u8)]
pub enum SocialLinkType {
    #[default]
    Mastodon = 1,
    Discord = 2,
    Website = 3,
    Facebook = 4,
    Twitter = 5,
    Instagram = 6,
    Patreon = 7,
    Twitch = 8,
    Reddit = 9,
    Youtube = 10,
    TikTok = 11,
    Pinterest = 12,
    Github = 13,
    Bluesky = 14,
}

impl std::fmt::Display for SocialLinkType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            Self::Mastodon => "1",
            Self::Discord => "2",
            Self::Website => "3",
            Self::Facebook => "4",
            Self::Twitter => "5",
            Self::Instagram => "6",
            Self::Patreon => "7",
            Self::Twitch => "8",
            Self::Reddit => "9",
            Self::Youtube => "10",
            Self::TikTok => "11",
            Self::Pinterest => "12",
            Self::Github => "13",
            Self::Bluesky => "14",
        })
    }
}

