/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.250410
 * 
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SocialLink {
    #[serde(rename = "type")]
    pub r#type: models::SocialLinkType,
    #[serde(rename = "url")]
    pub url: ::url::Url,
}

impl SocialLink {
    #[allow(clippy::too_many_arguments)]
    pub fn new(r#type: models::SocialLinkType, url: ::url::Url) -> Self {
        Self {
            r#type,
            url,
        }
    }
}

