/*
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SortableGameVersion {
    /// Original version name (e.g. 1.5b)
    #[serde(rename = "gameVersionName")]
    pub game_version_name: String,
    /// Used for sorting (e.g. 0000000001.0000000005)
    #[serde(rename = "gameVersionPadded")]
    pub game_version_padded: String,
    /// game version clean name (e.g. 1.5)
    #[serde(rename = "gameVersion")]
    pub game_version: String,
    /// Game version release date
    #[serde(rename = "gameVersionReleaseDate")]
    pub game_version_release_date: String,
    /// Game version type id
    #[serde(rename = "gameVersionTypeId", skip_serializing_if = "Option::is_none")]
    pub game_version_type_id: Option<u32>,
}

impl SortableGameVersion {
    pub fn new(game_version_name: String, game_version_padded: String, game_version: String, game_version_release_date: String) -> Self {
        Self {
            game_version_name,
            game_version_padded,
            game_version,
            game_version_release_date,
            game_version_type_id: None,
        }
    }
}

