name: ci
on:
  workflow_dispatch:
  pull_request:
  push:
    paths:
      - Cargo.lock
      - "**/Cargo.toml"
      - "*.toml"
      - "**.rs"
      - .github/workflows/ci.yml
    branches:
      - main
  schedule:
    - cron: "03 02 01 * *"

permissions:
  contents: read

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
      - name: Check formatting
        uses: actions-rust-lang/rustfmt@v1

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: clippy
      - name: Lint code
        run: cargo clippy --locked --release --verbose --workspace --exclude '*-client'

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Check documentation
        run: cargo doc --no-deps --document-private-items --locked --release --verbose --workspace

  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        rust:
          # MSRV
          - 1.80.0
          - stable
          - beta
          - nightly
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
      - name: build
        run: cargo build --locked --release --verbose --workspace
      - name: test
        run: cargo test --locked --release --verbose --workspace
