name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    paths:
      - "**/Cargo.lock"
      - "**/Cargo.toml"
      - "*.toml"
      - "**.rs"
      - .github/workflows/ci.yml
      - .github/workflows/build.yml
    branches:
      - main
  schedule:
    - cron: "03 02 * * 06"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  rustfmt:
    if: github.event_name != 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
      - name: Check formatting
        uses: actions-rust-lang/rustfmt@v1

  clippy:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: clippy
      - name: Lint code
        run: cargo clippy --no-deps --locked --verbose --workspace --all-features --all-targets

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Check documentation
        run: |
          cargo test --doc --locked --release --verbose --workspace --all-features
          cargo doc --no-deps --document-private-items --locked --verbose --workspace

  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        rust:
          # MSRV
          - 1.80.0
          - stable
          - beta
          - nightly
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
      - name: test
        run: cargo test --locked --release --verbose --workspace --all-features --all-targets --no-fail-fast

  build:
    uses: ./.github/workflows/build.yml
    with:
      dry-run: true
