name: Release
on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: cli/CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    needs: create-release
    permissions:
      contents: write
    secrets: inherit
    uses: ./.github/workflows/build.yml
    with:
      dry-run: false
